#%RAML 0.8
title: PSX Example api
baseUri: http://example.phpsx.org
version: v1
/population:
  description: Returns a collection of population entries
  get:
    responses:
      200:
        body:
          application/json:
            schema: !include schema/collection.json
  post:
    body:
      application/json:
        schema: !include schema/entry.json
    responses:
      201:
        body:
          application/json:
            schema: !include schema/message.json
/population/{id}:
  description: Returns a single population entry
  uriParameters:
    id:
      type: integer
  get:
    responses:
      200:
        body:
          application/json:
            schema: !include schema/entry.json
  put:
    body:
      application/json:
        schema: !include schema/entry.json
    responses:
      200:
        body:
          application/json:
            schema: !include schema/message.json
  delete:
    responses:
      200:
        body:
          application/json:
            schema: !include schema/message.json

